### ISSUE TITLE
TD-24 Проверить покрытие тестами, поправить сломавшиеся тесты

### ISSUE THREAD

**Issue by djud17** [djud17-org/todoList#57]
Проверить покрытие тестами (оба цикла сцен должны быть покрыты тестами, все сервисы)
Поправить тесты, которые могут сломаться в процессе

**Comment by SShliakhin** [comment]
Все тесты в рабочем состоянии.
- произведен запуск всех тестов
- качество не проверялось
- покрытость проверялась визуально



![Image](https://user-images.githubusercontent.com/71236551/229754198-5cdea4c3-efbf-44b8-8a34-4854fc8cba95.png)



![Image](https://user-images.githubusercontent.com/71236551/229754348-93c4f2c5-4020-468c-a4ec-716ca2ddef62.png)
